apiVersion: v1
kind: Service
metadata:
  name: stream-train-crawl-service
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: stream-train-crawl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-train-crawl
  labels:
    app: stream-train-crawl
    version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream-train-crawl
  template:
    metadata:
      labels:
        app: stream-train-crawl
    spec:
      containers:
      - name: stream-train-crawl
        image: corvimae/stream-train-crawl:latest
        ports:
        - containerPort: 3000